### ISSUE TITLE
NullPointerException when selecting single image from gallery with multiselect allowed

### ISSUE THREAD

**Issue by NoHarmDan** [jkwiecien/EasyImage#112]
Hi,

I ran into the following issue - when using the gallery to select multiple files, all works just fine, but when I select only one, an exception occurs while receiving the intent. Selecting single file works fine when multiselect is disabled - although the gallery application still allows me to select multiple files and when I do, I only get one file in the callback, which doesn't actually exist on the device and causes exceptions when I try to manipulate it. The fact it allows me to select multiple files with multiselect disabled is also a major issue.

The configuration and call are as follows:
```
EasyImage.configuration(getActivity())
                        .saveInRootPicturesDirectory()
                        .setCopyExistingPicturesToPublicLocation(false);

EasyImage.openGallery(this, 0, true);

```

And the stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
    at pl.aprilapps.easyphotopicker.EasyImage.onPictureReturnedFromGallery(EasyImage.java:356)
    at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.java:285)
    at cz.mobilesoft.photouploader.base.fragment.NumberOrderFragment.onActivityResult(NumberOrderFragment.java:128)
    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:167)
    at cz.mobilesoft.toorsfotouploader.activity.MainActivity.onActivityResult(MainActivity.java:106)
    at android.app.Activity.dispatchActivityResult(Activity.java:7022)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4248)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4295)
    at android.app.ActivityThread.-wrap20(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6290)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
So apparently the clipData is null in this method of the library:
```
private static void onPictureReturnedFromGallery(Intent data, Activity activity, Callbacks callbacks) {
        try {
            ClipData clipData = data.getClipData();
            List<File> files = new ArrayList<>();
            for (int i = 0; i < clipData.getItemCount(); i++) {
                Uri uri = clipData.getItemAt(i).getUri();
                File file = EasyImageFiles.pickedExistingPicture(activity, uri);
                files.add(file);
            }

            callbacks.onImagesPicked(files, ImageSource.GALLERY, restoreType(activity));
        } catch (Exception e) {
            e.printStackTrace();
            callbacks.onImagePickerError(e, ImageSource.GALLERY, restoreType(activity));
        }
    }

```

PS: I'm running the app on OnePlus 3, Android 7.1.1, project compile, target and build SDK version all set to API 25 - if that's any help.

**Comment by NoHarmDan** [comment]
Turns out it's just because the single file Uri is returned in the Data, not ClipData.

I propose a solution:
```
 private static void onPictureReturnedFromGallery(Intent data, Activity activity, Callbacks callbacks) {
        try {
            List<File> files = new ArrayList<>();

            ClipData clipData = data.getClipData();

            if (clipData == null) {
                Uri uri = data.getData();
                File file = EasyImageFiles.pickedExistingPicture(activity, uri);
                files.add(file);
            } else for (int i = 0; i < clipData.getItemCount(); i++) {
                Uri uri = clipData.getItemAt(i).getUri();
                File file = EasyImageFiles.pickedExistingPicture(activity, uri);
                files.add(file);
            }

            callbacks.onImagesPicked(files, ImageSource.GALLERY, restoreType(activity));
        } catch (Exception e) {
            e.printStackTrace();
            callbacks.onImagePickerError(e, ImageSource.GALLERY, restoreType(activity));
        }
    }

```

And the same but the other way around should apply in all other selection cases - since some gallery applications seem to ignore the ALLOW_MULTIPLE tag and allow multiple by default, causing a problem exact opposite to this one.

**Comment by NoHarmDan** [comment]
Wait why the hell is this solution actually present in the current version here but not in the gradle plugin? Just like the different configuration, which is actually described in the readme.
