### ISSUE TITLE
Null pointer exception in saveInAppExternalFilesDir() method

### ISSUE THREAD

**Issue by rastogitech** [jkwiecien/EasyImage#130]
Hi, I'm using following line in my Application class's onCreate() method:

`        EasyImage.configuration(this).saveInAppExternalFilesDir().setImagesFolderName("/ByDay/Recipes");
`

This give NPE on some devices. I tested on API level 19 emulator and got this:

```
Failed to execute task.
                                                              java.util.concurrent.TimeoutException
                                                                  at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                  at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:40)
                                                                  at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:278)
                                                                  at com.crashlytics.android.core.CrashlyticsController$5.onUncaughtException(CrashlyticsController.java:262)
                                                                  at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                  at dalvik.system.NativeStart.main(Native Method)
10-24 15:26:27.252 2763-2763/com.app.byday E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.app.byday, PID: 2763
                                                             java.lang.RuntimeException: Unable to create application com.common.App: java.lang.NullPointerException
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.lang.NullPointerException
                                                                 at pl.aprilapps.easyphotopicker.EasyImage$Configuration.saveInAppExternalFilesDir(EasyImage.java:405)
                                                                 at com.common.App.onCreate(App.java:59)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by jkwiecien** [comment]
Does it still happen on the latest version? What are the known devices it happens for

**Comment by rastogitech** [comment]
It happened on Nexus 5x. It's extreme issue. It's no more happening now.
