### ISSUE TITLE
NULL pointer (loadXmlMetaData)

### ISSUE THREAD

**Issue by gilshallem** [jkwiecien/EasyImage#133]
here is the error from crashlitics:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
       at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
       at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
       at pl.aprilapps.easyphotopicker.EasyImageFiles.getUriToFile(EasyImageFiles.java:142)
       at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:56)
       at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:116)
       at pl.aprilapps.easyphotopicker.EasyImage.openChooserWithGallery(EasyImage.java:190)
       at com.gilapps.smsshare2.customize.MyDetailsFragment.onPhotoClick(MyDetailsFragment.java:136)
       at com.gilapps.smsshare2.customize.MyDetailsFragment_ViewBinding$1.doClick(MyDetailsFragment_ViewBinding.java:40)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:6207)
       at android.view.View$PerformClick.run(View.java:23639)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by dhruvins7** [comment]
Hey @jkwiecien  , @gilshallem ,

Did you happen to find any solution to this?
