### ISSUE TITLE
Failure delivering result ResultInfo{who=null, request=72996, result=-1, data=null} when image is captured by camera

### ISSUE THREAD

**Issue by buelersandra** [jkwiecien/EasyImage#135]
After image is captured by camere using openChooserWithGallery i get the below error 

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=72996, result=-1, data=null} to activity {ana.foodi/ana.foodi.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

**Comment by feyzullahyildiz** [comment]
I'm using kotlin, emulator api 25, I call openCamera(this, 11) like this. I get this error on onActivityResult. Intent equals null and the request code is different.

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9068, result=-1, data=null} to activity {com.example.ahmet.ankasaha/com.example.ahmet.ankasaha.GalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

**Comment by AlexisQapa** [comment]
Same here did you manage to solve it ?

**Comment by zirkler** [comment]
Same here.

**Comment by tk2232** [comment]
Same here.

**Comment by maccam04** [comment]
Modify openCamera and openGallery if you are using fragment.

This is my preferred solution: 
from this :
`` public static void openCamera(Fragment fragment, int type) {
        Intent intent = createCameraIntent(fragment.getActivity(), type);
        fragment.startActivityForResult(intent, RequestCodes.TAKE_PICTURE);
    }
    ```
to
public static void openCamera(Fragment fragment, Context context, int type) {
        Intent intent = createCameraIntent(context, type);
        fragment.startActivityForResult(intent, RequestCodes.TAKE_PICTURE);
    }

```

and its working. :+1:

**Comment by iad24** [comment]
@feyzullahyildiz same here. I use Kotlin and hit this issue.
I even created a simple app from scratch.

It crashes when this is added:
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {
    super.onActivityResult(requestCode, resultCode, data)
    Log.d("super.onActivityResult", "requestCode=$requestCode, resultCode=$resultCode")
}
```
If I comment this, no crash.

```
Process: easyimage.sample.com.android.easyimageapp, PID: 31122
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7459, result=-1, data=null} to activity {easyimage.sample.com.android.easyimageapp/easyimage.sample.com.android.easyimageapp.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at easyimage.sample.com.android.easyimageapp.MainActivity.onActivityResult(MainActivity.kt:0)
        at android.app.Activity.dispatchActivityResult(Activity.java:7256)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```


Have u managed to fix this?

**Comment by wixche** [comment]
在kotlin中这个问题有可能是因为用户点击弹窗外部区域取消操作时data为空
只需要在onActivityResult中将数据定义为可空，安装如下方式修改即可
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)
