### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by vinaydahiwale** [jkwiecien/EasyImage#137]
12-19 10:45:25.323 22792-22792/com.kotak.aof E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.kotak.aof, PID: 22792
                                                              java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.kotak.aof/com.kotak.aof.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
                                                                  at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                  at android.support.v4.content.FileProvider.b(SourceFile:584)
                                                                  at android.support.v4.content.FileProvider.a(SourceFile:558)
                                                                  at android.support.v4.content.FileProvider.a(SourceFile:400)
                                                                  at org.apache.cordova.camera.CameraLauncher.takePicture(SourceFile:295)
                                                                  at org.apache.cordova.camera.CameraLauncher.onRequestPermissionResult(SourceFile:1315)
                                                                  at org.apache.cordova.CordovaInterfaceImpl.onRequestPermissionResult(SourceFile:214)
                                                                  at org.apache.cordova.CordovaActivity.onRequestPermissionsResult(SourceFile:508)

**Comment by axper** [comment]
Same problem here.

**Comment by iad24** [comment]
Another one here
