### ISSUE TITLE
Image Capture from Camera does not return image

### ISSUE THREAD

**Issue by shripal17** [jkwiecien/EasyImage#140]
When I select Camera to take pictures, the image gets clicked, but neither of the methods onImagePickerError nor onImagesPicked gets called and ultimately i do not receive the captured image

**Comment by shripal17** [comment]
API 26 Xiaomi Mi A1 Stock Android

**Comment by MNikdan** [comment]
i faced the same thing. but i realized when it returns from camera, inside onActivityResult, data is null. my mistake was before i call the EasyImage.handleActivityResult, i checked if data==null then return.

**Comment by yusufceylan** [comment]
Same here, I take picture, onImagePicked method triggered but device not saved image to gallery

Device Xiaomi Mi A2 Lite - 8.1.0

**Comment by kanblack** [comment]
I faced the same problem here. API 27, Nexus 6P, happend when using Google Camera App. If take picture by another app like Open Camera, the function working normally.

**Comment by wantroba** [comment]
Seme problem here! I tested in a Motorola g4 play XT1603 and didn't work. Also I tested in a Samsung Galaxy A5 (2017) SM-A520F and worked.

Here is the backtrace with the error:

2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err: kotlin.KotlinNullPointerException
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPicturesFromLocalStorage(EasyImage.kt:155)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPictures(EasyImage.kt:185)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onFileReturnedFromChooser(EasyImage.kt:233)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.kt:140)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at br.com.flowing.ui.activities.SettingsEditProfileActivity.onActivityResult(SettingsEditProfileActivity.java:633)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6946)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6165)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
2019-07-31 10:07:08.744 28615-28615/br.com.flowing W/System.err: kotlin.KotlinNullPointerException
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPicturesFromLocalStorage(EasyImage.kt:155)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPictures(EasyImage.kt:185)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onFileReturnedFromChooser(EasyImage.kt:233)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.kt:140)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at br.com.flowing.ui.activities.SettingsEditProfileActivity.onActivityResult(SettingsEditProfileActivity.java:633)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6946)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6165)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
2019-07-31 10:07:08.745 28615-28615/br.com.flowing W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by MishalAlchemy** [comment]
Any solution as per discussion above description.
I'm facing the same issue not working on Redmi 7 device 
Camera capture not working.

**Comment by bearlysophisticated** [comment]
As per my research, default Camera app (in my case Nexus devices and emulator) return with an empty Intent (Intent#data = null). This case not handled. My PR above is about to fix this.

**Comment by jkwiecien** [comment]
MErged https://github.com/jkwiecien/EasyImage/pull/216

**Comment by o-nos** [comment]
still have data == null when I make photo, man :(
