### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by iamarjun** [jkwiecien/EasyImage#187]
Hi, I'm trying to inject this EasyImage instead of creating new instances everytime, but somehow i'm not able to do the same.
`2019-05-09 12:29:33.997 17781-17781/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.momentsnap.android.stag, PID: 17781
    java.lang.RuntimeException: Unable to get provider pl.aprilapps.easyphotopicker.EasyImageFileProvider: java.lang.ClassNotFoundException: Didn't find class "pl.aprilapps.easyphotopicker.EasyImageFileProvider" on path: DexPathList[[zip file "/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/lib/arm64, /system/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6650)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6175)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6081)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.aprilapps.easyphotopicker.EasyImageFileProvider" on path: DexPathList[[zip file "/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at android.support.v4.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6634)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6175) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6081) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6923) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 14 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.momentsnap.android.stag-V4GLMUXh-fLcKvUmDY8wyQ==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 17 more`
Does anyone know what am i missing ?

**Comment by benjaminlefevre** [comment]
same issue, how do you solve it?

**Comment by AlvaroSanzRodrigo** [comment]
i got the same issue, no idea what to do

**Comment by khaledkhj** [comment]
sorry if it is late but just run through same problem and here is how to solve it (in case someone is looking for it)

you need to configure Kotlin in your project
https://stackoverflow.com/a/44583514

in fact, there was an issue on this problem
https://github.com/jkwiecien/EasyImage/issues/182
