### ISSUE TITLE
Chooser Mode Missing scenarios?

### ISSUE THREAD

**Issue by enizbilgin** [jkwiecien/EasyImage#206]
In some devices in chooser mode select camera.  ResultIntent not null  onActivityResult. 

```
   if (resultIntent != null) {
            onPickedExistingPictures(resultIntent, activity, callbacks)
            removeCameraFileAndCleanup()
        } else if (lastCameraFile != null) {
            onPictureReturnedFromCamera(activity, callbacks)
        }
```

at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPicturesFromLocalStorage(Easy
at pl.aprilapps.easyphotopicker.EasyImage.onPickedExistingPictures(EasyImage.kt:201)
at pl.aprilapps.easyphotopicker.EasyImage.onFileReturnedFromChooser(EasyImage.kt:249)
at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.kt:156)

**Comment by jkwiecien** [comment]
Merged https://github.com/jkwiecien/EasyImage/pull/207/
