### ISSUE TITLE
setCopyImagesToPublicGalleryFolder(true) not working on Android 10

### ISSUE THREAD

**Issue by peshkira** [jkwiecien/EasyImage#210]
When targeting Android 10 the images are not copied to the public PICTURES directory, because the destination directory is not accessible anymore.

`Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)` is deprecated and does not return a writable folder. This results in an io exception.

```
W/System.err: java.io.IOException: No such file or directory
W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err:     at java.io.File.createNewFile(File.java:1008)
W/System.err:     at pl.aprilapps.easyphotopicker.Files$copyFilesInSeparateThread$1.run(Files.kt:64)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
W/System.err:     at pl.aprilapps.easyphotopicker.Files.copyFilesInSeparateThread$library_release(Files.kt:74)
W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPictureReturnedFromCamera(EasyImage.kt:220)
W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onFileReturnedFromChooser(EasyImage.kt:252)
W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.kt:156)
```

**Comment by SamYStudiO** [comment]
Anyone has a patch for this?

**Comment by SamYStudiO** [comment]
In addition there something wrong with generate path that seems to prevent viewing files
`val extension = "." + filenameSplit[filenameSplit.size - 1]
                val datePart = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Calendar.getInstance().time)
                val filename = "IMG_${datePart}_$i.$extension%d.%s"`

what %d.%s stands for?
also the extension var and the filename var both add "." for extension.

**Comment by GiacomoDB** [comment]
Second this, the images are been saved with this weird extension.
IMG_20200508_145648_1..jpg%d.%s 
And this prevents them from been displayed in the gallery

**Comment by rollin-s** [comment]
When are you planning to merge this into the 3.0.5 version ? 

Is there any easy and quick fix without waiting for the new version ?

**Comment by gorshkoov** [comment]
If you need a quick fix, you can set ` android:requestLegacyExternalStorage="true"` to your AndroidMainfest application tag. But this will work until you change the target SDK.

The key of the problem is `getExternalStoragePublicDirectory` function. In Android 10 you should use scoped storage instead.
