### ISSUE TITLE
java.lang.SecurityException: Permission Denial:opening provider pl.aprilapps.easyphotopicker.EasyImageFileProvider

### ISSUE THREAD

**Issue by hafiz013** [jkwiecien/EasyImage#222]
Error come out when to open camera and take picture in xiomi android 6. Why?

`Process: com.android.camera, PID: 6127
java.lang.SecurityException: Permission Denial: opening provider pl.aprilapps.easyphotopicker.EasyImageFileProvider from ProcessRecord{c43094b 6127:com.android.camera/u0a23} (pid=6127, uid=10023) that is not exported from uid 10238
    at android.os.Parcel.readException(Parcel.java:1620)
    at android.os.Parcel.readException(Parcel.java:1573)
    at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3725)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:4915)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2031)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1497)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:968)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:726)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:702)
    at com.android.camera.module.CameraModule.doAttach(CameraModule.java:3115)
    at com.android.camera.module.CameraModule.onReviewDoneClicked(CameraModule.java:3048)
    at com.android.camera.fragment.FragmentBottomIntentDone.onClick(FragmentBottomIntentDone.java:104)
    at android.view.View.performClick(View.java:5215)
    at android.view.View$PerformClick.run(View.java:21196)
    at android.os.Handler.handleCallback(Handler.java:742)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5603)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)`

**Comment by hafiz013** [comment]
as suggestion: https://stackoverflow.com/questions/46785237/permission-for-an-image-from-gallery-is-lost-after-re-launch
https://stackoverflow.com/questions/37409181/java-lang-securityexception-permission-denial-opening-provider

**Comment by hafiz013** [comment]
mybe i believe different lvl android got has different way?

https://stackoverflow.com/questions/18847302/securityexception-permission-denial-opening-provider

**Comment by hafiz013** [comment]
@jkwiecien please help. This is bacause bugs happen in android 8.1 as well.
