### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(int, int, android.content.Intent, android.app.Activity, pl.aprilapps.easyphotopicker.EasyImage$Callbacks)' on a null object reference

### ISSUE THREAD

**Issue by SagarBChauhan** [jkwiecien/EasyImage#228]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34962, result=-1, data=Intent { dat=content://media/external/images/media/17060 flg=0x1 (has extras) }} to activity {com.allpracticals/com.allpracticals.EasyImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(int, int, android.content.Intent, android.app.Activity, pl.aprilapps.easyphotopicker.EasyImage$Callbacks)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(int, int, android.content.Intent, android.app.Activity, pl.aprilapps.easyphotopicker.EasyImage$Callbacks)' on a null object reference
        at com.allpracticals.EasyImageActivity.onActivityResult(EasyImageActivity.java:100)
        at android.app.Activity.dispatchActivityResult(Activity.java:8292)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7814) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by SagarBChauhan** [comment]
solved!

**Comment by popnitesh** [comment]
Who ? Sent from Mail for Windows 10 From: Sagar Bharatbhai ChauhanSent: 03 October 2020 18:22To: jkwiecien/EasyImageCc: SubscribedSubject: Re: [jkwiecien/EasyImage] java.lang.NullPointerException: Attempt to invoke virtual method 'void pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(int, int, android.content.Intent, android.app.Activity, pl.aprilapps.easyphotopicker.EasyImage$Callbacks)' on a null object reference (#228) solved!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Mouadabdelghafouraitali** [comment]
Hi @SagarBChauhan could you please share with us the solution.
