### ISSUE TITLE
Unable to open camera in android 11 

### ISSUE THREAD

**Issue by chikka** [jkwiecien/EasyImage#249]
I am facing issue in device with android 11. I have below code to open camera

```
EasyImage.Builder(this)

            .setChooserType(ChooserType.CAMERA_AND_GALLERY)

            .allowMultiple(false)
            .setStateHandler(this)
            .build()
```

and I am trying to open camera with below code

`easyImage!!.openCameraForImage(this)`

It is not opening camera nor giving any error

**Comment by sahithiganta** [comment]
I am also facing the similar issue could someone please respond ASAP

**Comment by ChetanPatelSS** [comment]
Unable to open camera in android 11 

I am also facing the similar issue could someone please respond ASAP

**Comment by alanastone** [comment]
I'm using an old version of the library (2.1.0) but I was having the same issue, what solved for me was adding this piece of code on my AndroidManifest:

```
<queries>
    <intent>
        <action android:name="android.media.action.IMAGE_CAPTURE" />
    </intent>
</queries>
```

If the `queries` tag doesn't compile for you try to use one of those Android Gradle Plugin versions: 3.3.3, 3.4.3, 3.5.4, 3.6.4, 4.0.1.

**Comment by OlukaDenis** [comment]
I'm facing the same issue.

**Comment by gringofe** [comment]
[Here's an article which attempts to implement a fix](https://newbedev.com/android-11-r-return-empty-list-when-querying-intent-for-action-image-capture)

**Comment by RyugaBahira** [comment]
> I'm using an old version of the library (2.1.0) but I was having the same issue, what solved for me was adding this piece of code on my AndroidManifest:
> 
> ```
> <queries>
>     <intent>
>         <action android:name="android.media.action.IMAGE_CAPTURE" />
>     </intent>
> </queries>
> ```
> 
> If the `queries` tag doesn't compile for you try to use one of those Android Gradle Plugin versions: 3.3.3, 3.4.3, 3.5.4, 3.6.4, 4.0.1.

it's working..thx

**Comment by Zhuinden** [comment]
So I got this

```
2021-12-11 07:55:48.112 25858-25858/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.GoogleCamera, PID: 25858
    java.lang.SecurityException: Permission Denial: writing androidx.core.content.FileProvider uri content://___.easyphotopicker.fileprovider/root/data/data/___/cache/EasyImage/ei_16389174189976121307593732602523.jpg from pid=25858, uid=10064 requires the provider be exported, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
        at oqy.b(PG:65)
        at enp.m(PG:52)
        at enj.onShutterButtonClick(PG:8)
        at keg.onShutterButtonClick(PG:4)
        at com.google.android.apps.camera.ui.shutterbutton.ShutterButton.performClick(PG:208)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

So you need to export the content provider to work on Android 12.
