### ISSUE TITLE
NullPointerException when external storage is not mounted

### ISSUE THREAD

**Issue by rciovati** [jkwiecien/EasyImage#38]
Calling `EasyImage.openChooser` when the external storage is not mounted throws this exception:

```
java.lang.NullPointerException
 at pl.aprilapps.easyphotopicker.EasyImageFiles.getFolderLocation(EasyImageFiles.java:98)
 at pl.aprilapps.easyphotopicker.EasyImageFiles.getCameraPicturesLocation(EasyImageFiles.java:103)
 at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:59)
 at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:85)
 at pl.aprilapps.easyphotopicker.EasyImage.openChooser(EasyImage.java:150)
 [omitted]
```

I'm not sure how the library should handle this situation though. IHMO the possibilities are:
* Use a `FileProvider` and let the camera save the image in the app internal folder.
* Skip the camera intent (and let the user just select the image from gallery/documents).

**Comment by jkwiecien** [comment]
How do you achieve that? I was under the impression that devices that has no built-in-external memory are old as world itself.

**Comment by rciovati** [comment]
Well, they are of course old but it's a situation that can actually happen :)

**Comment by jfbibeau** [comment]
For what it's worth, my Android emulator got in this state too and the library was constantly crashing with an NPE. Caused me a ton of headaches :(
