### ISSUE TITLE
Different directories to read and write [device-specific]

### ISSUE THREAD

**Issue by majaDeSmart** [jkwiecien/EasyImage#45]
java.io.IOException: open failed: ENOENT (No such file or directory)
at java.io.File.createNewFile(File.java:940)
at java.io.File.createTempFile(File.java:1005)
at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:80)
at pl.aprilapps.easyphotopicker.EasyImage.createCameraIntent(EasyImage.java:92)
at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:187)
[...]
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
at java.io.File.createNewFile(File.java:933)

AND

java.io.FileNotFoundException: *{file path - used saveInAppExternalFilesDir() configuration with custom folder name}*: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:416)
at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
at pl.aprilapps.easyphotopicker.EasyImage.onPictureReturnedFromGallery(EasyImage.java:298)

Both occurred on **HTC Desire X, Android 4.1.1**

**Comment by jkwiecien** [comment]
Try 1.3.0
