### ISSUE TITLE
[NullPointerException] openChooseWithGallery

### ISSUE THREAD

**Issue by TurhanOz** [jkwiecien/EasyImage#53]
Hello, 

Some runtime exception being raised by the root call openChooseWithGallery()

Caused by java.lang.NullPointerException
       at pl.aprilapps.easyphotopicker.EasyImageFiles.getFolderLocation(EasyImageFiles.java:100)
       at pl.aprilapps.easyphotopicker.EasyImageFiles.getCameraPicturesLocation(EasyImageFiles.java:105)
       at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:49)
       at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:91)
       at pl.aprilapps.easyphotopicker.EasyImage.openChooserWithGallery(EasyImage.java:155)

Cheers

**Comment by jkwiecien** [comment]
Need more details. System, device, version of a library
