### ISSUE TITLE
NullPointerException saveInAppExternalFilesDir

### ISSUE THREAD

**Issue by toby78** [jkwiecien/EasyImage#62]
```
Caused by java.lang.NullPointerException
       at pl.aprilapps.easyphotopicker.EasyImage$Configuration.saveInAppExternalFilesDir(EasyImage.java:376)
       at app.flirtbox.dating.ui.start.AuthenticatorActivity.onCreate(AuthenticatorActivity.java:102)
       at android.app.Activity.performCreate(Activity.java:5258)
```

**Comment by jkwiecien** [comment]
Try 1.3.0, it uses FIlePRovider, might solve that issue. If that doesnt help, I'll reopen.
