### ISSUE TITLE
IllegalArgumentException: Failed to find configured root that contains

### ISSUE THREAD

**Issue by Kaminiak** [jkwiecien/EasyImage#78]
Andorid: 6.0

When I call: `EasyImage.openChooserWithDocuments(this, "Select image", 0);`, I get:

```
 java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/31AB-1310/Android/data/com.example.myapp/cache/EasyImage/a9c926ea-4dce-44b7-94e9-a5dca6b91a5d-450242437.jpg
                                                                           at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
                                                                           at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                                                                           at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:54)
                                                                           at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:109)
                                                                           at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:103)
                                                                           at pl.aprilapps.easyphotopicker.EasyImage.openChooserWithDocuments(EasyImage.java:147)
                                                                           at com.example.myapp.screens.watch.WatchActivity.showPhotoPicker(WatchActivity.java:120)
                                                                           at com.example.myapp.screens.watch.state.WatchIdleState.onImageClicked(WatchIdleState.java:28)
                                                                           at com.example.myapp.screens.watch.WatchActivity.onImageClicked(WatchActivity.java:116)
                                                                           at com.example.myapp.screens.watch.WatchActivity$$ViewBinder$1.doClick(WatchActivity$$ViewBinder.java:35)
                                                                           at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                           at android.view.View.performClick(View.java:5273)
                                                                           at android.view.View$PerformClick.run(View.java:21315)
                                                                           at android.os.Handler.handleCallback(Handler.java:743)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:150)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5639)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

I have added CAMERA and WRITE_EXTERNAL_STORAGE permissions, and they are accepted. Ask if you need some more information.

**Comment by FrankZhang007** [comment]
me too....

**Comment by tanxiaoluo** [comment]
I meet with the same problem.

**Comment by tanxiaoluo** [comment]
I think i may find how this happen and how to solve it.

At first, you need kown "later versions of KitKat no longer support the user foreign buy SDcard (Secondary Storage) of write operation"


	Failed to find configured root that contains /storage/31AB-1310/Android/data/com.example.myapp/cache

this is a storage address and is confined .So we can wirte date in Internal storage.

You just need to remove those code in EasyImageFiles.java

	if (isExternalStorageWritable()) {
		cacheDir = context.getExternalCacheDir();
	}

**Comment by benznest** [comment]
I have same problem.

**Comment by benznest** [comment]
@Kaminiak Can you solve this problem? please help me about the error.

**Comment by benznest** [comment]
@tanxiaoluo  How to remove those code in that file?

**Comment by tanxiaoluo** [comment]
@benznest delete or annotation it, like this:
```
//if (isExternalStorageWritable()) {
//    cacheDir = context.getExternalCacheDir();
//}
```
this problem happen when you set your Default Location as SD card.
Because FileProvider cannot access SD card.

**Comment by jkwiecien** [comment]
Any of you have an actuall idea how to fix it? Some pr maybe?

**Comment by sprimgupta** [comment]
Same problem Here , Any proper way to fix this problem for files in sdcard ?

**Comment by vipulasri** [comment]
Having the same problem. Is there a fix?

**Comment by ezcoding** [comment]
@jkwiecien can't we just skip writing on the external dir and save the file internally directly, just as @tanxiaoluo suggested.

I'm affected by this problem too and the "advantage" of storing the temporary file on the external storage is not really an advantage, if this crashing bug can't be fixed for several months, because we don't have an actual idea how to fix it.

How do you fell about it?

**Comment by SirLordPouya** [comment]
same problem here. any fix?

**Comment by proninyaroslav** [comment]
@SirLordPouya Please see https://github.com/jkwiecien/EasyImage/pull/144.

**Comment by Ali-Kheiri** [comment]
I have same problem 
I guess this problem can be about recognizing correct directory path...
