### ISSUE TITLE
Crash when opening image chooser with sdk version 25

### ISSUE THREAD

**Issue by andi3** [jkwiecien/EasyImage#79]
After updating to android sdk 25 the image chooser does not work any more:

<pre><code>E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.example.app, PID: 706
                  java.lang.NoClassDefFoundError: pl.aprilapps.easyphotopicker.EasyImageFiles
                      at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:51)
                      at pl.aprilapps.easyphotopicker.EasyImage.createChooserIntent(EasyImage.java:109)
                      at pl.aprilapps.easyphotopicker.EasyImage.openChooserWithGallery(EasyImage.java:174)
                      at de.example.app.activities.UserUpdateActivity$4.onClick(UserUpdateActivity.java:144)
                      at android.view.View.performClick(View.java:4438)
                      at android.view.View$PerformClick.run(View.java:18422)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)</code></pre>

compileSdkVersion: 25
targetSdkVersion: 25
compile 'com.github.jkwiecien:EasyImage:1.3.1'
android support versions: 25.0.0
buildToolsVersion 25.0.0
classpath 'com.android.tools.build:gradle:2.2.2'

**Comment by jkwiecien** [comment]
What was the device you were using? Working fine on my 5X running 7.0. Were you running 7.1 preview?

**Comment by andi3** [comment]
I was struggling three days with this problem and it turned out that it was a multidex problem. Sorry, not the fault of the lib. Because of the "pl." package name the classes where in the second .dex file and where not found by older devices like API 19

**Comment by brspurri** [comment]
@andi3 I'm having the same issue. What exactly was wrong with your multidex? At current, I have no idea how to fix this.

**Comment by andi3** [comment]
The problem was that the "pl." package of this library was compiled into the second .dex file. Since I use an API version below 20, I forgot to include the following into my Application class: 
```
public class MyApplication extends SomeOtherApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(context);
     Multidex.install(this);
  }
}
```

The `Multidex.install(this);` line is the solution ;)

**Comment by brspurri** [comment]
That did it! Thanks for the pointer!!!! Huge help.
